# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de2dd568ca2fc10217b60cf9580d9abdd2a3cfd687f199b6bbac69b6e0540929b9a235dd061f100487b91cacb75806358c55272f46bc3c5fafecbbeee32769f

test:
  secret_key_base: bd4a7a5b7081a275f322b2df4b1e5c69d3a503a5b4619409c1c4649e2e557fb8bbdfac0da63026d6ed95a3f4ac48177a1a25e584136c64d9ea7415c32700250d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
